### ISSUE TITLE
모듈/패키지 불러오기

### ISSUE THREAD

**Issue by dragonteros** [dragonteros/unsuspected-hangeul#2]
안녕하세요..? 고수 여러분들의 도움이 필요합니다ㅜㅜ
제가 PL을 막 들은 가엾은 학부생이라서 기본적인 것 이상으로 나아가는 데 한계를 느끼고 있습니다ㅜㅜ
불러오기도 그 중에 하나인데요..
구문은 아마 기본 제공 함수 5번 (ㅂ; 불러오기) 호출이 될 것 같습니다.

1. 패키지/모듈 정의
제가 아는 게 거의 파이썬뿐이라서...
우선은 파이썬처럼 파일이랑 디렉토리 단위로 패키지/모듈이라고 생각하면 될까 싶은데,
이게 괜찮은 건가요? 더 나은 방법이 있을까요?

2. 또 파일 단위로 한다면, 한 파일 안에 여러 객체가 나열되는 경우를 허용하는 게 나을까요?
만약 그렇게 한다면 아마 모듈을 Closure객체로서 불러와서 여기다 번호로 인덱싱을 하거나
아니면 여기에 별도의 기본 함수를 배당하거나, 아니면 불러올 때부터 번호를 지정해 그것만 가져오는 방식들이 생각이 납니다. 어느 게 제일 좋을까요? 아니면 다른 방법이 더 있을까요?

3. 문법
기본 함수 ㅂ에는 어떤 인수를 넣는 형식이 되는 게 좋을까요?

4. 행동
가령 '무슨_모듈 ㅂ ㅎ무슨_숫자'로 모듈을 불러왔다고 하고 잠시 이걸 x라고 이름붙이면, 이것의 사용법은 어떻게 되어야 할까요?

**Comment by iwyoo** [comment]
1. 괜찮은 것 같습니다! 그냥 import를 몇 단계로 나누느냐 정도의 차이라, 디렉토리로 묶으면 더 들어가야 하는 정도라고 생각합니다. 그런데 이것도 __init__.py을 어떻게 세팅하느냐에 따라 차이가 많아서, 프로젝트 크기가 작으면 크게 상관 없을 것 같습니다.
2. 파일 안에는 연관된 객체들만 같이 들어있는게 좋아 보입니다. 파일 하나에서 뭐가 많이 있다면 __all__을 지정해서 import를 제한하는 것도 좋고요. 단순하게 import 하지 않고 동적으로 import 하는 방법을 생각하신다면 importlib 같은 걸 이용하는 것도 좋습니다. 구현에 맞게 사용하시면 됩니다.
```
# ex.
# 간단한 방법.
from A import Aclass # 특정 대상을 직접 명시
a = Aclass()

# 팩토리 패턴
from A import builder_A # 팩토리를 사용
a = builder_A("Aclass")

# importlib
import importlib
module = importlib.import_module("A")
a = getattr(module, "Aclass")()
```
이외에도 다양한 방법이 있겠지만 편리한 방법을 찾아 쓰시면 됩니다
3~4. 기본 함수 ㅂ에 대한 명세를 찾기 어렵네요! 다른 언어의 let과 같은 함수인가요?

**Comment by dragonteros** [comment]
@iwyoo 친절한 답변 감사드립니다! XD 많은 공부가 되었어요
3, 4번은 다름이 아니라 다른 사람이 쓴 '평범한 한글' 객체를 불러오는 기능을 새로 만들어서 기본함수 ㅂ이라고 부르려고 하는데 문법이나 행동 등등을 결정하는 데 어려움이 있어서 같이 머리를 모아주십사 한 것이었습니다 :D

**Comment by iwyoo** [comment]
아, 좀 잘못 읽고 댓글을 달았었네요 (ㅠㅠ
꼭 파이썬처럼 해야할 필요는 없을 것 같긴 합니다. 파일을 가져와서 indexing하는게 가장 무난할 것 같아요.
가령 각 줄을 번호를 매겨서 특정 라인의 함수나 값을 가져오는 식으로요.
예) (모듈) ㅂㄱ -> 모듈의 0번째줄 반환
문자열이 지원된다면 다른 방식으로 접근하는 것도 가능할 것 같네요

**Comment by dragonteros** [comment]
제 생각에도 파일을 가져와서 내용물에 번호를 매기는 게 좋을 것 같아요.
그러면 top-level에 있는 객체들에 번호를 매기는 식이 될 것 같습니다.
불러올 때 행동을 이렇게 세 가지를 생각을 하고 있습니다.
1. 불러올 때 원하는 객체만 콕 집어 가져오는 방안
2. wrapper 함수 형태로 불러와 여기에 번호를 인수로 넣어 호출하면 원하는 객체가 나오는 방안
3. 아예 class/object를 새로운 자료형으로 도입해서 모듈을 불러온 뒤 어느 지정된 기본함수로 원하는 속성과 메소드를 불러오는 방안
파이썬으로 비유를 하면 1안은 from module_name import object_name에 해당하겠고 2안은 앞서 말씀하신 빌더 패턴을 언어 차원에서 지원하는 것과 비슷하겠고, 3안은 import module_name으로 불러와 module_name.object_name으로 사용하는 것에 해당하겠습니다.
미래를 생각하면 3안을 택하는 게 이로울 것 같지만 도입되기까지 시간이 오래 걸릴 것으로 예상되고, 1, 2안은 당장 구현하기는 더 쉬울 것 같은데 나중에 class를 도입할 때 일관성이 깨질 수 있을 것 같다는 생각이 듭니다.
어떻게 하는 게 가장 좋을까요?

**Comment by iwyoo** [comment]
모듈 자체도 하나의 객체로 보는 게 옳다는 생각이 들어 1안보다는 2,3안이 더 좋을 것 같습니다.
사실 2,3안은 함수에 이름을 붙이는 것을 얼마나 허용하느냐의 차이 같아요.
매번 (모듈이름) ㅂ 으로 불러오고 뒤에 정수를 붙여 내용에 접근하는 것도 가능할 것 같지만, (2안)
(모듈이름) ㅂ 자체를 특정이름(변수)에 할당해두고 (그런 기능을 만든다면 3안이 되겠지요)
사용할 수도 있을 것 같습니다.

**Comment by andrea9292** [comment]
저는 3안에 찬성합니다. 지금의 평범한 한글은 굉장히 정제되어 있고 아름답습니다. 시간이 걸리더라도 모듈을 불러오는 기능보다는 사용자 정의 자료형을 쓸 수 있도록 평범한 한글의 외연을 넓히는 것은 어떨까요? 당장 객체페 이름 붙이기(#8) 논점에서도 말씀드린 내용이지만 이후 평범한 한글의 방향성을 설정한다는 점에서 시간이 걸리더라도 차근차근 쌓아나가는 것도 좋다고 생각합니다.

그리고, 외부 파일을 지칭해야 한다면 결국 언어 자원의 문자열 기능 지원도 필요해 보입니다. 지금은 한글 이외의 모든 문자를 무시하지만, 결국 문자열이나 주석 등을 다루려면 평범한 한글에서 최소한의 예약된 기호를 도입해야 할지도 모르겠습니다. 이 문제는 별도의 논점을 열어서 의논해야 할지도 모르겠네요. 좀 더 생각을 정리해서 어떤 문법으로 만들면 좋겠는지 올려보겠습니다.

**Comment by dragonteros** [comment]
@andrea9292 사용자 정의 자료형 명세(안) 논점(#9)을 새로 열었습니다.

다른 한편으로, 제가 2월과 생각이 달라진 부분이 있는데, 어차피 프로그램의 최상위에 객체를 여러 개 늘어놓으면 그 객체들은 서로를 인식하지 못하기 때문에 별개의 파일로 분리해둔 것과 차이가 없다고 생각해서, 모듈으로 묶이려면 클래스든 함수든 하나의 객체가 되어야한다고 생각했습니다. 그렇다면 그 객체만 콕 집어 불러오는 게 제일 타당하다고 생각하고 있습니다.
