### ISSUE TITLE
사용자로부터 입력 받기

### ISSUE THREAD

**Issue by kmc7468** [dragonteros/unsuspected-hangeul#3]
안녕하세요. 언어 스펙에 `stdin` 이나 그 외에 스트림으로부터 입력을 받는 기능이 있으면 좋을 것 같아 이슈를 엽니다. 감사합니다.

**Comment by dragonteros** [comment]
stdin에서 읽어오는 기능을 기본 함수 3번 (ㄹ)에 추가하겠습니다. 감사합니다!
