### ISSUE TITLE
기본함수 목록 ㄱㄱ, ㅈㄱ

### ISSUE THREAD

**Issue by iwyoo** [dragonteros/unsuspected-hangeul#6]
https://github.com/dragonteros/unsuspected-hangeul/wiki/%EA%B8%B0%EB%B3%B8-%ED%95%A8%EC%88%98-%EB%AA%A9%EB%A1%9D
기본함수 목록 위키에 ㄱㄱ과 ㅈㄱ은 없는 것 같은데 혹시 이유가 있나요?

**Comment by dragonteros** [comment]
특별한 이유는 없습니다. 혹시 제안하실 기능이 있으신가요?

**Comment by iwyoo** [comment]
아, 위키 목록에 '미정'으로도 안 돼 있고 칸 자체가 없어 문법적인 이유가 있나 해서 질문드렸습니다

**Comment by dragonteros** [comment]
알려주셔서 감사합니다. ㅈㄱ은 실수로 누락되었고, 지금 고쳤습니다.
ㄱㄱ(-0)은 ㄱ(+0)과 구분하지 않아 따로 칸이 없습니다.
